# Generated by Django 5.0.6 on 2025-12-25 23:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('normalized_url', models.CharField(editable=False, max_length=255, unique=True)),
                ('last_status_code', models.IntegerField(blank=True, null=True)),
                ('last_response_time', models.FloatField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('ssl_valid_from', models.DateTimeField(blank=True, null=True)),
                ('ssl_valid_to', models.DateTimeField(blank=True, null=True)),
                ('ssl_days_left', models.IntegerField(blank=True, null=True)),
                ('ssl_status', models.CharField(blank=True, max_length=50, null=True)),
                ('domain_expiration', models.DateTimeField(blank=True, null=True)),
                ('domain_days_left', models.IntegerField(blank=True, null=True)),
                ('domain_status', models.CharField(default='UNKNOWN', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('content_snippet', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitor.site')),
            ],
            options={
                'verbose_name': 'Проверка сайта',
                'verbose_name_plural': 'История проверок',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('chat_id', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.URLField(verbose_name='URL')),
                ('last_status_code', models.IntegerField(blank=True, null=True, verbose_name='Последний статус')),
                ('last_response_time', models.FloatField(blank=True, null=True, verbose_name='Последнее время ответа (сек.)')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('last_content_snippet', models.TextField(blank=True, verbose_name='Фрагмент последнего ответа')),
                ('ssl_valid_from', models.DateTimeField(blank=True, null=True)),
                ('ssl_valid_to', models.DateTimeField(blank=True, null=True)),
                ('ssl_days_left', models.IntegerField(blank=True, null=True)),
                ('ssl_status', models.CharField(blank=True, max_length=50, null=True)),
                ('domain_expiration', models.DateTimeField(blank=True, null=True)),
                ('domain_days_left', models.IntegerField(blank=True, null=True)),
                ('domain_status', models.CharField(default='UNKNOWN', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='websites', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название у пользователя')),
                ('notify_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='monitor.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'site')},
            },
        ),
        migrations.AddConstraint(
            model_name='website',
            constraint=models.UniqueConstraint(fields=('user', 'url'), name='unique_site_per_user'),
        ),
    ]
