# Generated by Django 5.0.6 on 2025-11-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
                ('last_status_code', models.IntegerField(blank=True, null=True, verbose_name='Последний статус')),
                ('last_response_time', models.FloatField(blank=True, null=True, verbose_name='Последнее время ответа (сек.)')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('last_content_snippet', models.TextField(blank=True, verbose_name='Фрагмент последнего ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты',
                'ordering': ['-created_at'],
            },
        ),
    ]
