# Generated by Django 5.0.6 on 2025-12-08 15:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, verbose_name='Telegram Bot Token')),
                ('chat_id', models.CharField(max_length=50, verbose_name='Telegram Chat ID')),
            ],
            options={
                'verbose_name': 'Telegram настройки',
                'verbose_name_plural': 'Telegram настройки',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
                ('last_status_code', models.IntegerField(blank=True, null=True, verbose_name='Последний статус')),
                ('last_response_time', models.FloatField(blank=True, null=True, verbose_name='Последнее время ответа (сек.)')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('last_content_snippet', models.TextField(blank=True, verbose_name='Фрагмент последнего ответа')),
                ('ssl_valid_from', models.DateTimeField(blank=True, null=True)),
                ('ssl_valid_to', models.DateTimeField(blank=True, null=True)),
                ('ssl_days_left', models.IntegerField(blank=True, null=True)),
                ('ssl_status', models.CharField(blank=True, max_length=50, null=True)),
                ('domain_expiration', models.DateTimeField(blank=True, null=True)),
                ('domain_days_left', models.IntegerField(blank=True, null=True)),
                ('domain_status', models.CharField(default='UNKNOWN', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('content_snippet', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitor.website')),
            ],
            options={
                'verbose_name': 'Проверка сайта',
                'verbose_name_plural': 'История проверок',
                'ordering': ['-checked_at'],
            },
        ),
    ]
