# Generated by Django 5.0.6 on 2025-12-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsettings',
            name='notify_down',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='telegramsettings',
            name='notify_timeout',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='telegramsettings',
            name='notify_up',
            field=models.BooleanField(default=True),
        ),
    ]
