# Generated by Django 5.0.6 on 2025-11-23 18:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('content_snippet', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitor.website')),
            ],
            options={
                'verbose_name': 'Проверка сайта',
                'verbose_name_plural': 'История проверок',
                'ordering': ['-checked_at'],
            },
        ),
    ]
