# Generated by Django 5.0.6 on 2026-01-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_telegramsettings_notify_down_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsettings',
            name='email_enabled',
            field=models.BooleanField(default=False, verbose_name='Отправлять уведомления на email'),
        ),
        migrations.AlterField(
            model_name='telegramsettings',
            name='chat_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='telegramsettings',
            name='token',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
