# Generated by Django 5.0.6 on 2025-11-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_websitecheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='ssl_days_left',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='ssl_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='ssl_valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='ssl_valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
