# Generated by Django 5.0.6 on 2025-11-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_website_ssl_days_left_website_ssl_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, verbose_name='Telegram Bot Token')),
                ('chat_id', models.CharField(max_length=50, verbose_name='Telegram Chat ID')),
            ],
            options={
                'verbose_name': 'Telegram настройки',
                'verbose_name_plural': 'Telegram настройки',
            },
        ),
    ]
