# Generated by Django 5.0.6 on 2025-12-12 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_website_url_website_unique_site_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('normalized_url', models.CharField(max_length=255, unique=True)),
                ('last_status_code', models.IntegerField(blank=True, null=True)),
                ('last_response_time', models.FloatField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('ssl_valid_from', models.DateTimeField(blank=True, null=True)),
                ('ssl_valid_to', models.DateTimeField(blank=True, null=True)),
                ('ssl_days_left', models.IntegerField(blank=True, null=True)),
                ('ssl_status', models.CharField(blank=True, max_length=50, null=True)),
                ('domain_expiration', models.DateTimeField(blank=True, null=True)),
                ('domain_days_left', models.IntegerField(blank=True, null=True)),
                ('domain_status', models.CharField(default='UNKNOWN', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название у пользователя')),
                ('notify_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='monitor.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'site')},
            },
        ),
    ]
