# Generated by Django 5.0.6 on 2026-01-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_telegramsettings_email_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес сайта'),
        ),
    ]
