# Generated by Django 5.0.6 on 2025-11-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_telegramsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='domain_days_left',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='domain_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='domain_status',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
    ]
