# Generated by Django 5.0.6 on 2026-01-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_site_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='ip_asn',
            field=models.CharField(blank=True, max_length=50, verbose_name='ASN'),
        ),
        migrations.AddField(
            model_name='site',
            name='ip_country',
            field=models.CharField(blank=True, max_length=2, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='site',
            name='ip_provider',
            field=models.CharField(blank=True, max_length=255, verbose_name='Провайдер / организация'),
        ),
        migrations.AddField(
            model_name='site',
            name='ipinfo_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
