# Generated by Django 5.0.6 on 2025-12-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_website_domain_days_left_website_domain_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='domain_status',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
    ]
