# Generated by Django 5.0.6 on 2026-01-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_site_ip_asn_site_ip_country_site_ip_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='avg_response_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Среднее время отклика (сек.)'),
        ),
        migrations.AddField(
            model_name='site',
            name='median_response_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Медианное время отклика (сек.)'),
        ),
    ]
