# Generated by Django 5.0.6 on 2026-05-07 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_site_avg_response_time_site_median_response_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Включить email-уведомления')),
                ('notify_down', models.BooleanField(default=True, verbose_name='Падение сайта')),
                ('notify_up', models.BooleanField(default=True, verbose_name='Восстановление сайта')),
                ('notify_timeout', models.BooleanField(default=True, verbose_name='Таймаут / недоступен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
